version: 2.1

orbs:
  python: circleci/python@2.1.1
  aws-cli: circleci/aws-cli@2.0

jobs:
  build-and-test:
    # ... (previous build-and-test job remains unchanged)

  deploy-to-eb:
    docker:
      - image: cimg/python:3.11.6
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup
      - run:
          name: Install AWS Elastic Beanstalk CLI
          command: |
            pip install awsebcli
      - run:
          name: Configure AWS credentials for Elastic Beanstalk
          command: |
            mkdir -p ~/.aws
            echo "[eb-cli]" > ~/.aws/credentials
            echo "aws_access_key_id = ${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
            echo "aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials
            echo "[profile eb-cli]" > ~/.aws/config
            echo "region = ${AWS_DEFAULT_REGION}" >> ~/.aws/config
      - run:
          name: Deploy to Elastic Beanstalk
          command: |
            eb use your-environment-name --profile eb-cli
            eb deploy --profile eb-cli

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: main
      - deploy-to-eb:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
