"""Initial migration.

Revision ID: b16b929e12d5
Revises: 007b59cc7d2d
Create Date: 2024-08-17 08:57:56.790076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b16b929e12d5'
down_revision = '007b59cc7d2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('revenue', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('rating')
        batch_op.drop_column('revenue')
        batch_op.drop_column('purchase_count')

    # ### end Alembic commands ###
